// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmsuYQEP6SH5Oq1FG8VKkn1yolI5zQBGI',
    appId: '1:180294149215:web:0396445b9500e0eb35e7ea',
    messagingSenderId: '180294149215',
    projectId: 'cgpa-app-9bf40',
    authDomain: 'cgpa-app-9bf40.firebaseapp.com',
    storageBucket: 'cgpa-app-9bf40.appspot.com',
    measurementId: 'G-TRSVFR9Y7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVRfiA06JUn1HYypQiVCApCKa06gLITyw',
    appId: '1:180294149215:android:61d39b09d9c6aaab35e7ea',
    messagingSenderId: '180294149215',
    projectId: 'cgpa-app-9bf40',
    storageBucket: 'cgpa-app-9bf40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJe01sOue2b60KvFNbktCTGcnsZVAOXAs',
    appId: '1:180294149215:ios:46806ece2407e36335e7ea',
    messagingSenderId: '180294149215',
    projectId: 'cgpa-app-9bf40',
    storageBucket: 'cgpa-app-9bf40.appspot.com',
    iosClientId: '180294149215-lf6lrsvpsq796kv2rj87ecri9nooie1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileDevCgpaApp',
  );
}
